ALTER TABLE buildings
    ADD COLUMN location_search VARCHAR(255) NULL,
    ADD COLUMN country VARCHAR(100) NULL,
    ADD COLUMN state VARCHAR(100) NULL,
    ADD COLUMN city VARCHAR(100) NULL,
    ADD COLUMN street VARCHAR(150) NULL,
    ADD COLUMN unit_location VARCHAR(50) NULL,
    ADD COLUMN zip VARCHAR(20) NULL;

ALTER TABLE units
    ADD COLUMN property_size VARCHAR(100) NULL,
    ADD COLUMN bathrooms INT NOT NULL DEFAULT 0,
    ADD COLUMN bedroom_details JSON NULL,
    ADD COLUMN base_price DECIMAL(10, 2) NULL,
    ADD COLUMN discounts JSON NULL;
